// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW1nM3K6QqREj74FuI39L1MxoX-cH2zok',
    appId: '1:619234152666:web:565016da8718298afb15e3',
    messagingSenderId: '619234152666',
    projectId: 'ltandroi-th5',
    authDomain: 'ltandroi-th5.firebaseapp.com',
    storageBucket: 'ltandroi-th5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbxU3X4PISb-FWxxyOHtI1nlkqXdah1lk',
    appId: '1:619234152666:android:0b7b087a6aeff7e2fb15e3',
    messagingSenderId: '619234152666',
    projectId: 'ltandroi-th5',
    storageBucket: 'ltandroi-th5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARwbn_4SmouhYKxt72w-BjpbwaIW8SDbM',
    appId: '1:619234152666:ios:880b1b9f4741d62afb15e3',
    messagingSenderId: '619234152666',
    projectId: 'ltandroi-th5',
    storageBucket: 'ltandroi-th5.firebasestorage.app',
    iosBundleId: 'com.example.quanlysinhvien',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARwbn_4SmouhYKxt72w-BjpbwaIW8SDbM',
    appId: '1:619234152666:ios:880b1b9f4741d62afb15e3',
    messagingSenderId: '619234152666',
    projectId: 'ltandroi-th5',
    storageBucket: 'ltandroi-th5.firebasestorage.app',
    iosBundleId: 'com.example.quanlysinhvien',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW1nM3K6QqREj74FuI39L1MxoX-cH2zok',
    appId: '1:619234152666:web:41f6347b87f64157fb15e3',
    messagingSenderId: '619234152666',
    projectId: 'ltandroi-th5',
    authDomain: 'ltandroi-th5.firebaseapp.com',
    storageBucket: 'ltandroi-th5.firebasestorage.app',
  );
}
